version: '3.8'

services:
  frontend:
    build: ./frontend-example-docker
    container_name: sonja-frontend
    ports:
      - '5000:5000'

  backend:
    build: ./backend-example-docker
    container_name: sonja-backend
    ports:
      - '8000:8000'
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=sonja
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sonja
