version: '3.8'

services:
  frontend:
    build: ./frontend-example-docker
    container_name: sonja-frontend
    environment:
      - API_URL=http://localhost/api/
    depends_on:
      - backend

  backend:
    build: ./backend-example-docker
    container_name: sonja-backend
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=sonja
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sonja
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
